const Footer = () => (
    <footer>
        <ul>
            <li>
                <ul>
                    <li><p>Test!</p></li>
                </ul>
                <ul>
                    <li><p>Test!</p></li>
                </ul>
                <ul>
                    <li><p>Test!</p></li>
                </ul>
                <ul>
                    <li><p>Test!</p></li>
                </ul>
                <ul>
                    <li><p>Test!</p></li>
                </ul>
                <ul>
                    <li><p>Test!</p></li>
                </ul>
                <ul>
                    <li><p>Test!</p></li>
                </ul>
            </li>
            <li>
                <ul>
                    <li><p>Footer Works!</p></li>
                </ul>
                <ul>
                    <li><p>Test!</p></li>
                </ul>
                <ul>
                    <li><p>Test!</p></li>
                </ul>
                <ul>
                    <li><p>Test!</p></li>
                </ul>
                <ul>
                    <li><p>Test!</p></li>
                </ul>
                <ul>
                    <li><p>Test!</p></li>
                </ul>
                <ul>
                    <li><p>Test!</p></li>
                </ul>
                <ul>
                    <li><p>Test!</p></li>
                </ul>
                <ul>
                    <li><p>Test!</p></li>
                </ul>
            </li>
            <li>
                <ul>
                    <li><p>Footer Works!</p></li>
                </ul>
                <ul>
                    <li><p>Test!</p></li>
                </ul>
                <ul>
                    <li><p>Test!</p></li>
                </ul>
                <ul>
                    <li><p>Test!</p></li>
                </ul>
                <ul>
                    <li><p>Test!</p></li>
                </ul>
                <ul>
                    <li><p>Test!</p></li>
                </ul>
                <ul>
                    <li><p>Test!</p></li>
                </ul>
                <ul>
                    <li><p>Test!</p></li>
                </ul>
            </li>
            <li>
                <ul>
                    <li><p>Footer Works!</p></li>
                </ul>
                <ul>
                    <li><p>Test!</p></li>
                </ul>
                <ul>
                    <li><p>Test!</p></li>
                </ul>
                <ul>
                    <li><p>Test!</p></li>
                </ul>
                <ul>
                    <li><p>Test!</p></li>
                </ul>
                <ul>
                    <li><p>Test!</p></li>
                </ul>
                <ul>
                    <li><p>Test!</p></li>
                </ul>
                <ul>
                    <li><p>Test!</p></li>
                </ul>
                <ul>
                    <li><p>Test!</p></li>
                </ul>
            </li>
        </ul>
        <hr />
        <ul>
            <li><img src='../public/IMG-20241109-WA0000.jpg' alt="Err" /></li>
            <li>
                <p>Get Apollo App on:</p>
                <div>
                    <p>Playstore</p>
                    <p>App store</p>
                </div>
            </li>
            <li>
                <p>Find us on</p>
                <div>
                    <p>SM Icons x4</p>
                </div>
            </li>
        </ul>
    </footer>
);

export default Footer